### ISSUE TITLE
ValueError: Invalid header value b'Bearer

### ISSUE THREAD

**Issue by chengtie** [daveshap/PythonGPT3Tutorial#1]
I would like to try your code.

I put my api key in `openaiapikey.txt` in the repository and run the follows, it gave me an error:

```
$ python hello_world.py
Traceback (most recent call last):
  File "hello_world.py", line 29, in <module>
    response = gpt3_completion(prompt)
  File "hello_world.py", line 22, in gpt3_completion
    stop=stop)
  File "/opt/anaconda3/lib/python3.7/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 122, in create
    request_timeout=request_timeout,
  File "/opt/anaconda3/lib/python3.7/site-packages/openai/api_requestor.py", line 179, in request
    request_timeout=request_timeout,
  File "/opt/anaconda3/lib/python3.7/site-packages/openai/api_requestor.py", line 363, in request_raw
    timeout=request_timeout if request_timeout else TIMEOUT_SECS,
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/opt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/anaconda3/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/lib/python3.7/http/client.py", line 1293, in _send_request
    self.putheader(hdr, value)
  File "/opt/anaconda3/lib/python3.7/http/client.py", line 1230, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'Bearer sk-4XXXXXXXXXXXXXXcpi\n'
```

Could you help?

**Comment by AAV-Christina** [comment]
Replace the following on line 9

openai.api_key = open_file('openaiapikey.txt')

with 

openai.api_key_path = 'openaiapikey.txt'

then it works great
